import turtle

def drawMaze():
	maze = turtle.Turtle()
	maze.color("red")
	maze.penup()
	maze.backward(175)
	maze.right(90)
	maze.forward(125)
	maze.speed(100)
	maze.pendown()
	maze.left(90)
	maze.forward(100)
	maze.left(90)
	maze.forward(50)
	maze.left(90)
	maze.forward(50)
	maze.right(90)
	maze.forward(100)
	maze.penup()
	maze.backward(100)
	maze.left(90)
	maze.backward(50)
	maze.right(90)
	maze.backward(50)
	maze.right(90)
	maze.backward(100)
	maze.pendown()
	maze.left(90)
	maze.forward(200)
	maze.right(90)
	maze.forward(100)
	maze.left(90)
	maze.forward(50)
	maze.left(90)
	maze.forward(50)
	maze.penup()
	maze.forward(50)
	maze.pendown()
	maze.right(90)
	maze.forward(50)
	maze.right(90)
	maze.forward(350)
	maze.backward(150)
	maze.right(90)
	maze.forward(100)
	maze.right(90)
	maze.forward(50)
	maze.right(90)
	maze.forward(50)
	maze.penup()
	maze.backward(50)
	maze.left(90)
	maze.backward(50)
	maze.left(90)
	maze.backward(100)
	maze.left(90)
	maze.forward(150)
	maze.pendown()
	maze.right(90)
	maze.forward(50)
	maze.right(90)
	maze.forward(50)
	maze.penup()
	maze.backward(50)
	maze.left(90)
	maze.pendown()
	maze.forward(100)
	maze.right(90)
	maze.forward(50)
	maze.penup()
	maze.backward(50)
	maze.left(90)
	maze.pendown()
	maze.forward(100)
	maze.penup()
	maze.forward(50)
	maze.pendown()
	maze.right(90)
	maze.forward(50)
	maze.right(90)
	maze.forward(100)
	maze.left(90)
	maze.forward(50)
	maze.left(90)
	maze.forward(50)
	maze.penup()
	maze.backward(50)
	maze.pendown()
	maze.backward(100)
	maze.left(90)
	maze.forward(50)
	maze.penup()
	maze.backward(50)
	maze.pendown()
	maze.left(90)
	maze.forward(50)
	maze.penup()
	maze.backward(150)
	maze.left(90)
	maze.backward(50)
	maze.left(90)
	maze.forward(100)
	maze.right(90)
	maze.pendown()
	maze.forward(100)
	maze.right(90)
	maze.forward(50)
	maze.left(90)
	maze.forward(50)
	maze.right(90)
	maze.forward(50)
	maze.left(90)
	maze.forward(50)
	maze.right(90)
	maze.forward(50)
	maze.penup()
	maze.backward(50)
	maze.left(90)
	maze.backward(50)
	maze.right(90)
	maze.backward(50)
	maze.left(90)
	maze.backward(50)
	maze.right(90)
	maze.pendown()
	maze.forward(100)
	maze.left(90)
	maze.forward(50)
	maze.penup()
	maze.backward(50)
	maze.right(90)
	maze.backward(150)
	maze.left(90)
	maze.pendown()
	maze.forward(100)
	maze.hideturtle()

def userControl():
	# W = up
	# A = left
	# S = down
	# D = right
	user = turtle.Turtle()
	user.penup()
	user.hideturtle()
	user.backward(175)
	user.left(90)
	user.forward(100)
	user.right(90)
	user.color("blue")
	user.shape("turtle")
	user.showturtle()
# Control Turtle	
	movement = input("Enter 'w', 'a', 's', 'd', or 'x'.")
	while (movement != 'x'):
		if (movement == 'w'):
			user.forward(10)
			movement = input("Enter 'w', 'a', 's', 'd', or 'x'.")
		elif(movement == 'a'):
			user.left(90)
			movement = input("Enter 'w', 'a', 's', 'd', or 'x'.")
		elif(movement == 's'):
			user.backward(10)
			movement = input("Enter 'w', 'a', 's', 'd', or 'x'.")
		elif(movement == 'd'):
			user.right(90)
			movement = input("Enter 'w', 'a', 's', 'd', or 'x'.")
	if(movement == 'x'):
		print("Great Job!")


def main():
	drawMaze()
	print("Guide the Turtle Through the Maze")
	print("w: Forward")
	print("a: Left Turn")
	print("s : Backward")
	print("d: Right Turn")
	print("x: Finished")
	userControl()
main()
